# Generated by Django 3.0.8 on 2020-08-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='zip_code',
            field=models.ManyToManyField(to='city_app.ZipCode'),
        ),
    ]
