# Generated by Django 3.0.8 on 2020-08-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_app', '0002_auto_20200801_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='zip_code',
            new_name='zip_codes',
        ),
    ]
