# Generated by Django 3.0.8 on 2020-08-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_app', '0004_auto_20200801_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='city',
            name='zip_codes',
            field=models.ManyToManyField(to='city_app.ZipCode'),
        ),
    ]
